### PR TITLE
Added backers and sponsors from OpenCollective

### PR DESCRIPTION
**Pull request by piamancini**
now sponsors & backers will show up in your readme and others can back you from here as well.

### CODE REVIEW

**Comment by alexhultman** [comment]
:)

**Comment by SEAPUNK** [comment]
Was this removed for a reason? I don't see a commit that does this (did you force push?)

**Comment by alexhultman** [comment]
I force pushed, yes. Reason would be that I don't think its needed.

**Comment by SEAPUNK** [comment]
Why not? Just wondering.

**Comment by eilatanwood** [comment]
Hello am not a robot willing to Skype appreciate my robot assume position to be sorted and fixed as soon as 

Cheers
Eilatan

**Comment by alexhultman** [comment]
Well, it makes me uneasy to take donations from private persons (this was never the intention), and I don't want to actively chase companies for sponsorship. If any company likes what I do here they should hire me instead. I started this project (and was paid for doing so) at my last workplace/employer. They needed scalable WebSockets and didn't care if I made this open source or not, so I did. Now, this company has gone "poof" and I'm currently not employed (as of the beginning of May).

I'm currently being interviewed by various companies and will be joining any of these any time soon (well, that is my plan at least). So I don't really have a real issue with funding right now and I would much rather have some company hire me to work with various stuff where WebSockets could be one of these things, instead of taking donations. I keep doing this because I find it amusing and any donations on top of this wouldn't change anything.

**Pull request merged**
